import {
  AddDuotoneIcon,
  AttendanceDuotoneIcon,
  BellDuotoneIcon,
  BoxDuotoneIcon,
  BuildingDuotoneIcon,
  CalendarArrowDuotoneIcon,
  CalendarCheckDuotoneIcon,
  CalendarCloseDuotoneIcon,
  CalendarDuotoneIcon,
  CalendarMinimalisticDuotoneIcon,
  CalendarPlusDuotoneIcon,
  CameraDuotoneIcon,
  CameraRotateDuotoneIcon,
  CardDuotoneIcon,
  ChatDuotoneIcon,
  CheckDuotoneIcon,
  ClipboardAddDuotoneIcon,
  ClipboardCheckDuotoneIcon,
  ClipboardEditDuotoneIcon,
  ClipboardListDuotoneIcon,
  ClipboardOkayDuotoneIcon,
  ClipboardSearchDuotoneIcon,
  ClipboardTextDuotoneIcon,
  ClipboardWarningDuotoneIcon,
  ClockCircleDuotoneIcon,
  CloseDuotoneIcon,
  CopyDuotoneIcon,
  DangerDuotoneIcon,
  DiagramUpDuotoneIcon,
  DialogDuotoneIcon,
  DisketteDuotoneIcon,
  DocumentAddDuotoneIcon,
  DocumentDuotoneIcon,
  DownloadDuotoneIcon,
  EmailDuotoneIcon,
  EyeClosedDuotoneIcon,
  EyeDuotoneIcon,
  FileDuotoneIcon,
  FilterDuotoneIcon,
  FolderDuotoneIcon,
  GalleryAddDuotoneIcon,
  GalleryDuotoneIcon,
  GlobalDuotoneIcon,
  GpsDuotoneIcon,
  GroupDuotoneIcon,
  HamburgerMenuDuotoneIcon,
  HashtagDuotoneIcon,
  HeartDuotoneIcon,
  HistoryDuotoneIcon,
  HomeDuotoneIcon,
  InfoDuotoneIcon,
  KeyDuotoneIcon,
  LinkDuotoneIcon,
  LoanSaleDuotoneIcon,
  LockKeyholeDuotoneIcon,
  LockKeyholeUnlockedDuotoneIcon,
  LoginDuotoneIcon,
  LogoutDuotoneIcon,
  MagnifierDuotoneIcon,
  MapPointDuotoneIcon,
  MinusDuotoneIcon,
  MyLoansDuotoneIcon,
  NotesDuotoneIcon,
  PaperclipDuotoneIcon,
  PayslipDuotoneIcon,
  PenDuotoneIcon,
  PhoneDuotoneIcon,
  PieChartDuotoneIcon,
  QrCodeDuotoneIcon,
  QuestionDuotoneIcon,
  ScannerDuotoneIcon,
  ScheduleDuotoneIcon,
  SettingsDuotoneIcon,
  ShieldCheckDuotoneIcon,
  ShopDuotoneIcon,
  ShoppingBasketDuotoneIcon,
  ShoppingCartDuotoneIcon,
  StarDuotoneIcon,
  SuitcaseDuotoneIcon,
  TrashDuotoneIcon,
  TuningSquareDuotoneIcon,
  UnlinkDuotoneIcon,
  UploadDuotoneIcon,
  UserDuotoneIcon,
  WalletDuotoneIcon,
  WidgetDuotoneIcon,
  AddFillIcon,
  ArrowDownFillIcon,
  ArrowLeftFillIcon,
  ArrowRightFillIcon,
  ArrowUpFillIcon,
  AttendanceFillIcon,
  BellFillIcon,
  BoxFillIcon,
  BuildingsFillIcon,
  CalendarArrowFillIcon,
  CalendarCheckFillIcon,
  CalendarCloseFillIcon,
  CalendarFillIcon,
  CalendarMinimalisticFillIcon,
  CalendarPlusFillIcon,
  CameraFillIcon,
  CameraRotateFillIcon,
  CardFillIcon,
  CaretDownFillIcon,
  CaretLeftFillIcon,
  CaretRightFillIcon,
  CaretUpFillIcon,
  ChatFillIcon,
  CheckFillIcon,
  ClipboardAddFillIcon,
  ClipboardCheckFillIcon,
  ClipboardEditFillIcon,
  ClipboardListFillIcon,
  ClipboardOkayFillIcon,
  ClipboardSearchFillIcon,
  ClipboardTextFillIcon,
  ClipboardTimeFillIcon,
  ClipboardWarningFillIcon,
  ClockCircleFillIcon,
  CloseFillIcon,
  CopyFillIcon,
  DangerFillIcon,
  DiagramUpFillIcon,
  DialogFillIcon,
  DisketteFillIcon,
  DocumentAddFillIcon,
  DocumentFillIcon,
  DoubleCaretDownFillIcon,
  DoubleCaretLeftFillIcon,
  DoubleCaretRightFillIcon,
  DoubleCaretUpFillIcon,
  DownloadFillIcon,
  EmailFillIcon,
  EyeClosedFillIcon,
  EyeFillIcon,
  FileFillIcon,
  FilterFillIcon,
  FolderFillIcon,
  GalleryAddFillIcon,
  GalleryFillIcon,
  GlobalFillIcon,
  GpsFillIcon,
  GroupFillIcon,
  HamburgerMenuFillIcon,
  HashtagFillIcon,
  HeartFillIcon,
  HistoryFillIcon,
  HomeFillIcon,
  InfoFillIcon,
  KeyFillIcon,
  LinkFillIcon,
  LoanSaleFillIcon,
  LockKeyholeFillIcon,
  LockKeyholeUnlockedFillIcon,
  LoginFillIcon,
  LogoutFillIcon,
  MagniferFillIcon,
  MapPointFillIcon,
  MenuDotFillIcon,
  MinusFillIcon,
  MyLoansFillIcon,
  NotesFillIcon,
  PaperclipFillIcon,
  PayslipFillIcon,
  PenFillIcon,
  PhoneFillIcon,
  PieChartFillIcon,
  QrCodeFillIcon,
  QuestionFillIcon,
  RefreshFillIcon,
  RestartFillIcon,
  ScannerFillIcon,
  ScheduleFillIcon,
  SettingsFillIcon,
  ShieldCheckFillIcon,
  ShopFillIcon,
  ShoppingBasketFillIcon,
  ShoppingCartFillIcon,
  StarFillIcon,
  SuitcaseFillIcon,
  TrashFillIcon,
  TuningSquareFillIcon,
  UnlinkFillIcon,
  UploadFillIcon,
  UserFillIcon,
  WalletFillIcon,
  WidgetFillIcon,
  AddOutlineIcon,
  ArrowDownOutlineIcon,
  ArrowLeftOutlineIcon,
  ArrowRightOutlineIcon,
  ArrowUpOutlineIcon,
  AttendanceOutlineIcon,
  BellOutlineIcon,
  BoxOutlineIcon,
  BuildingsOutlineIcon,
  CalendarArrowOutlineIcon,
  CalendarCheckOutlineIcon,
  CalendarCloseOutlineIcon,
  CalendarMinimalisticOutlineIcon,
  CalendarOutlineIcon,
  CalendarPlusOutlineIcon,
  CameraOutlineIcon,
  CameraRotateOutlineIcon,
  CardOutlineIcon,
  CaretDownOutlineIcon,
  CaretLeftOutlineIcon,
  CaretRightOutlineIcon,
  CaretUpOutlineIcon,
  ChatOutlineIcon,
  CheckOutlineIcon,
  ClipboardAddOutlineIcon,
  ClipboardCheckOutlineIcon,
  ClipboardEditOutlineIcon,
  ClipboardListOutlineIcon,
  ClipboardOkayOutlineIcon,
  ClipboardSearchOutlineIcon,
  ClipboardTextOutlineIcon,
  ClipboardTimeOutlineIcon,
  ClipboardWarningOutlineIcon,
  ClockCircleOutlineIcon,
  CloseOutlineIcon,
  CopyOutlineIcon,
  DangerOutlineIcon,
  DiagramUpOutlineIcon,
  DialogOutlineIcon,
  DisketteOutlineIcon,
  DocumentAddOutlineIcon,
  DocumentOutlineIcon,
  DoubleCaretDownOutlineIcon,
  DoubleCaretLeftOutlineIcon,
  DoubleCaretRightOutlineIcon,
  DoubleCaretUpOutlineIcon,
  DownloadOutlineIcon,
  EmailOutlineIcon,
  EyeClosedOutlineIcon,
  EyeOutlineIcon,
  FileOutlineIcon,
  FilterOutlineIcon,
  FolderOutlineIcon,
  GalleryAddOutlineIcon,
  GalleryOutlineIcon,
  GlobalOutlineIcon,
  GpsOutlineIcon,
  GroupOutlineIcon,
  HamburgerMenuOutlineIcon,
  HashtagOutlineIcon,
  HeartOutlineIcon,
  HistoryOutlineIcon,
  HomeOutlineIcon,
  InfoOutlineIcon,
  KeyOutlineIcon,
  LinkOutlineIcon,
  LoanSaleOutlineIcon,
  LockKeyholeOutlineIcon,
  LockKeyholeUnlockedOutlineIcon,
  LoginOutlineIcon,
  LogoutOutlineIcon,
  MagniferOutlineIcon,
  MapPointOutlineIcon,
  MenuDotOutlineIcon,
  MinusOutlineIcon,
  MyLoansOutlineIcon,
  NotesOutlineIcon,
  PaperclipOutlineIcon,
  PayslipOutlineIcon,
  PenOutlineIcon,
  PhoneOutlineIcon,
  PieChartOutlineIcon,
  QrCodeOutlineIcon,
  QuestionOutlineIcon,
  RefreshOutlineIcon,
  RestartOutlineIcon,
  ScannerOutlineIcon,
  ScheduleOutlineIcon,
  SettingsOutlineIcon,
  ShieldCheckOutlineIcon,
  ShopOutlineIcon,
  ShoppingBasketOutlineIcon,
  ShoppingCartOutlineIcon,
  StarOutlineIcon,
  SuitcaseOutlineIcon,
  TrashOutlineIcon,
  TuningSquareOutlineIcon,
  UnlinkOutlineIcon,
  UploadOutlineIcon,
  UserOutlineIcon,
  WalletOutlineIcon,
  WidgetOutlineIcon,
} from '../../assets/icons';

import type { IconProps, IconType } from './Icon.type';

export const Icon = ({ name, color, secondary, tertiary, size }: IconProps) => {
  const svgFillIconProps = {
    fill: color || '#8c8c8c',
    secondary: secondary || '#d9d9d9',
    tertiary: tertiary || '#f2f2f2',
    size,
  };

  const iconName: Record<IconType, JSX.Element> = {
    addDuotone: <AddDuotoneIcon {...svgFillIconProps} />,
    attendanceDuotone: <AttendanceDuotoneIcon {...svgFillIconProps} />,
    bellDuotone: <BellDuotoneIcon {...svgFillIconProps} />,
    boxDuotone: <BoxDuotoneIcon {...svgFillIconProps} />,
    buildingDuotone: <BuildingDuotoneIcon {...svgFillIconProps} />,
    calendarArrowDuotone: <CalendarArrowDuotoneIcon {...svgFillIconProps} />,
    calendarCheckDuotone: <CalendarCheckDuotoneIcon {...svgFillIconProps} />,
    calendarCloseDuotone: <CalendarCloseDuotoneIcon {...svgFillIconProps} />,
    calendarDuotone: <CalendarDuotoneIcon {...svgFillIconProps} />,
    calendarMinimalisticDuotone: (
      <CalendarMinimalisticDuotoneIcon {...svgFillIconProps} />
    ),
    calendarPlusDuotone: <CalendarPlusDuotoneIcon {...svgFillIconProps} />,
    cameraDuotone: <CameraDuotoneIcon {...svgFillIconProps} />,
    cameraRotateDuotone: <CameraRotateDuotoneIcon {...svgFillIconProps} />,
    cardDuotone: <CardDuotoneIcon {...svgFillIconProps} />,
    chatDuotone: <ChatDuotoneIcon {...svgFillIconProps} />,
    checkDuotone: <CheckDuotoneIcon {...svgFillIconProps} />,
    clipboardAddDuotone: <ClipboardAddDuotoneIcon {...svgFillIconProps} />,
    clipboardCheckDuotone: <ClipboardCheckDuotoneIcon {...svgFillIconProps} />,
    clipboardEditDuotone: <ClipboardEditDuotoneIcon {...svgFillIconProps} />,
    clipboardListDuotone: <ClipboardListDuotoneIcon {...svgFillIconProps} />,
    clipboardOkayDuotone: <ClipboardOkayDuotoneIcon {...svgFillIconProps} />,
    clipboardSearchDuotone: (
      <ClipboardSearchDuotoneIcon {...svgFillIconProps} />
    ),
    clipboardTextDuotone: <ClipboardTextDuotoneIcon {...svgFillIconProps} />,
    clipboardWarningDuotone: (
      <ClipboardWarningDuotoneIcon {...svgFillIconProps} />
    ),
    clockCircleDuotone: <ClockCircleDuotoneIcon {...svgFillIconProps} />,
    closeDuotone: <CloseDuotoneIcon {...svgFillIconProps} />,
    copyDuotone: <CopyDuotoneIcon {...svgFillIconProps} />,
    dangerDuotone: <DangerDuotoneIcon {...svgFillIconProps} />,
    diagramUpDuotone: <DiagramUpDuotoneIcon {...svgFillIconProps} />,
    dialogDuotone: <DialogDuotoneIcon {...svgFillIconProps} />,
    disketteDuotone: <DisketteDuotoneIcon {...svgFillIconProps} />,
    documentAddDuotone: <DocumentAddDuotoneIcon {...svgFillIconProps} />,
    documentDuotone: <DocumentDuotoneIcon {...svgFillIconProps} />,
    downloadDuotone: <DownloadDuotoneIcon {...svgFillIconProps} />,
    emailDuotone: <EmailDuotoneIcon {...svgFillIconProps} />,
    eyeClosedDuotone: <EyeClosedDuotoneIcon {...svgFillIconProps} />,
    eyeDuotone: <EyeDuotoneIcon {...svgFillIconProps} />,
    fileDuotone: <FileDuotoneIcon {...svgFillIconProps} />,
    filterDuotone: <FilterDuotoneIcon {...svgFillIconProps} />,
    folderDuotone: <FolderDuotoneIcon {...svgFillIconProps} />,
    galleryAddDuotone: <GalleryAddDuotoneIcon {...svgFillIconProps} />,
    galleryDuotone: <GalleryDuotoneIcon {...svgFillIconProps} />,
    globalDuotone: <GlobalDuotoneIcon {...svgFillIconProps} />,
    gpsDuotone: <GpsDuotoneIcon {...svgFillIconProps} />,
    groupDuotone: <GroupDuotoneIcon {...svgFillIconProps} />,
    hamburgerMenuDuotone: <HamburgerMenuDuotoneIcon {...svgFillIconProps} />,
    hashtagDuotone: <HashtagDuotoneIcon {...svgFillIconProps} />,
    heartDuotone: <HeartDuotoneIcon {...svgFillIconProps} />,
    historyDuotone: <HistoryDuotoneIcon {...svgFillIconProps} />,
    homeDuotone: <HomeDuotoneIcon {...svgFillIconProps} />,
    infoDuotone: <InfoDuotoneIcon {...svgFillIconProps} />,
    keyDuotone: <KeyDuotoneIcon {...svgFillIconProps} />,
    linkDuotone: <LinkDuotoneIcon {...svgFillIconProps} />,
    loanSaleDuotone: <LoanSaleDuotoneIcon {...svgFillIconProps} />,
    lockKeyholeDuotone: <LockKeyholeDuotoneIcon {...svgFillIconProps} />,
    lockKeyholeUnlockedDuotone: (
      <LockKeyholeUnlockedDuotoneIcon {...svgFillIconProps} />
    ),
    loginDuotone: <LoginDuotoneIcon {...svgFillIconProps} />,
    logoutDuotone: <LogoutDuotoneIcon {...svgFillIconProps} />,
    magnifierDuotone: <MagnifierDuotoneIcon {...svgFillIconProps} />,
    mapPointDuotone: <MapPointDuotoneIcon {...svgFillIconProps} />,
    minusDuotone: <MinusDuotoneIcon {...svgFillIconProps} />,
    myLoansDuotone: <MyLoansDuotoneIcon {...svgFillIconProps} />,
    notesDuotone: <NotesDuotoneIcon {...svgFillIconProps} />,
    paperclipDuotone: <PaperclipDuotoneIcon {...svgFillIconProps} />,
    payslipDuotone: <PayslipDuotoneIcon {...svgFillIconProps} />,
    penDuotone: <PenDuotoneIcon {...svgFillIconProps} />,
    phoneDuotone: <PhoneDuotoneIcon {...svgFillIconProps} />,
    pieChartDuotone: <PieChartDuotoneIcon {...svgFillIconProps} />,
    qrCodeDuotone: <QrCodeDuotoneIcon {...svgFillIconProps} />,
    questionDuotone: <QuestionDuotoneIcon {...svgFillIconProps} />,
    scannerDuotone: <ScannerDuotoneIcon {...svgFillIconProps} />,
    scheduleDuotone: <ScheduleDuotoneIcon {...svgFillIconProps} />,
    settingsDuotone: <SettingsDuotoneIcon {...svgFillIconProps} />,
    shieldCheckDuotone: <ShieldCheckDuotoneIcon {...svgFillIconProps} />,
    shopDuotone: <ShopDuotoneIcon {...svgFillIconProps} />,
    shoppingBasketDuotone: <ShoppingBasketDuotoneIcon {...svgFillIconProps} />,
    shoppingCartDuotone: <ShoppingCartDuotoneIcon {...svgFillIconProps} />,
    starDuotone: <StarDuotoneIcon {...svgFillIconProps} />,
    suitcaseDuotone: <SuitcaseDuotoneIcon {...svgFillIconProps} />,
    trashDuotone: <TrashDuotoneIcon {...svgFillIconProps} />,
    tuningSquareDuotone: <TuningSquareDuotoneIcon {...svgFillIconProps} />,
    unlinkDuotone: <UnlinkDuotoneIcon {...svgFillIconProps} />,
    uploadDuotone: <UploadDuotoneIcon {...svgFillIconProps} />,
    userDuotone: <UserDuotoneIcon {...svgFillIconProps} />,
    walletDuotone: <WalletDuotoneIcon {...svgFillIconProps} />,
    widgetDuotone: <WidgetDuotoneIcon {...svgFillIconProps} />,
    addFill: <AddFillIcon {...svgFillIconProps} />,
    arrowDownFill: <ArrowDownFillIcon {...svgFillIconProps} />,
    arrowLeftFill: <ArrowLeftFillIcon {...svgFillIconProps} />,
    arrowRightFill: <ArrowRightFillIcon {...svgFillIconProps} />,
    arrowUpFill: <ArrowUpFillIcon {...svgFillIconProps} />,
    attendanceFill: <AttendanceFillIcon {...svgFillIconProps} />,
    bellFill: <BellFillIcon {...svgFillIconProps} />,
    boxFill: <BoxFillIcon {...svgFillIconProps} />,
    buildingsFill: <BuildingsFillIcon {...svgFillIconProps} />,
    calendarArrowFill: <CalendarArrowFillIcon {...svgFillIconProps} />,
    calendarCheckFill: <CalendarCheckFillIcon {...svgFillIconProps} />,
    calendarCloseFill: <CalendarCloseFillIcon {...svgFillIconProps} />,
    calendarFill: <CalendarFillIcon {...svgFillIconProps} />,
    calendarMinimalisticFill: (
      <CalendarMinimalisticFillIcon {...svgFillIconProps} />
    ),
    calendarPlusFill: <CalendarPlusFillIcon {...svgFillIconProps} />,
    cameraFill: <CameraFillIcon {...svgFillIconProps} />,
    cameraRotateFill: <CameraRotateFillIcon {...svgFillIconProps} />,
    cardFill: <CardFillIcon {...svgFillIconProps} />,
    caretDownFill: <CaretDownFillIcon {...svgFillIconProps} />,
    caretLeftFill: <CaretLeftFillIcon {...svgFillIconProps} />,
    caretRightFill: <CaretRightFillIcon {...svgFillIconProps} />,
    caretUpFill: <CaretUpFillIcon {...svgFillIconProps} />,
    chatFill: <ChatFillIcon {...svgFillIconProps} />,
    checkFill: <CheckFillIcon {...svgFillIconProps} />,
    clipboardAddFill: <ClipboardAddFillIcon {...svgFillIconProps} />,
    clipboardCheckFill: <ClipboardCheckFillIcon {...svgFillIconProps} />,
    clipboardEditFill: <ClipboardEditFillIcon {...svgFillIconProps} />,
    clipboardListFill: <ClipboardListFillIcon {...svgFillIconProps} />,
    clipboardOkayFill: <ClipboardOkayFillIcon {...svgFillIconProps} />,
    clipboardSearchFill: <ClipboardSearchFillIcon {...svgFillIconProps} />,
    clipboardTextFill: <ClipboardTextFillIcon {...svgFillIconProps} />,
    clipboardTimeFill: <ClipboardTimeFillIcon {...svgFillIconProps} />,
    clipboardWarningFill: <ClipboardWarningFillIcon {...svgFillIconProps} />,
    clockCircleFill: <ClockCircleFillIcon {...svgFillIconProps} />,
    closeFill: <CloseFillIcon {...svgFillIconProps} />,
    copyFill: <CopyFillIcon {...svgFillIconProps} />,
    dangerFill: <DangerFillIcon {...svgFillIconProps} />,
    diagramUpFill: <DiagramUpFillIcon {...svgFillIconProps} />,
    dialogFill: <DialogFillIcon {...svgFillIconProps} />,
    disketteFill: <DisketteFillIcon {...svgFillIconProps} />,
    documentAddFill: <DocumentAddFillIcon {...svgFillIconProps} />,
    documentFill: <DocumentFillIcon {...svgFillIconProps} />,
    doubleCaretDownFill: <DoubleCaretDownFillIcon {...svgFillIconProps} />,
    doubleCaretLeftFill: <DoubleCaretLeftFillIcon {...svgFillIconProps} />,
    doubleCaretRightFill: <DoubleCaretRightFillIcon {...svgFillIconProps} />,
    doubleCaretUpFill: <DoubleCaretUpFillIcon {...svgFillIconProps} />,
    downloadFill: <DownloadFillIcon {...svgFillIconProps} />,
    emailFill: <EmailFillIcon {...svgFillIconProps} />,
    eyeClosedFill: <EyeClosedFillIcon {...svgFillIconProps} />,
    eyeFill: <EyeFillIcon {...svgFillIconProps} />,
    fileFill: <FileFillIcon {...svgFillIconProps} />,
    filterFill: <FilterFillIcon {...svgFillIconProps} />,
    folderFill: <FolderFillIcon {...svgFillIconProps} />,
    galleryAddFill: <GalleryAddFillIcon {...svgFillIconProps} />,
    galleryFill: <GalleryFillIcon {...svgFillIconProps} />,
    globalFill: <GlobalFillIcon {...svgFillIconProps} />,
    gpsFill: <GpsFillIcon {...svgFillIconProps} />,
    groupFill: <GroupFillIcon {...svgFillIconProps} />,
    hamburgerMenuFill: <HamburgerMenuFillIcon {...svgFillIconProps} />,
    hashtagFill: <HashtagFillIcon {...svgFillIconProps} />,
    heartFill: <HeartFillIcon {...svgFillIconProps} />,
    historyFill: <HistoryFillIcon {...svgFillIconProps} />,
    homeFill: <HomeFillIcon {...svgFillIconProps} />,
    infoFill: <InfoFillIcon {...svgFillIconProps} />,
    keyFill: <KeyFillIcon {...svgFillIconProps} />,
    linkFill: <LinkFillIcon {...svgFillIconProps} />,
    loanSaleFill: <LoanSaleFillIcon {...svgFillIconProps} />,
    lockKeyholeFill: <LockKeyholeFillIcon {...svgFillIconProps} />,
    lockKeyholeUnlockedFill: (
      <LockKeyholeUnlockedFillIcon {...svgFillIconProps} />
    ),
    loginFill: <LoginFillIcon {...svgFillIconProps} />,
    logoutFill: <LogoutFillIcon {...svgFillIconProps} />,
    magniferFill: <MagniferFillIcon {...svgFillIconProps} />,
    mapPointFill: <MapPointFillIcon {...svgFillIconProps} />,
    menuDotFill: <MenuDotFillIcon {...svgFillIconProps} />,
    minusFill: <MinusFillIcon {...svgFillIconProps} />,
    myLoansFill: <MyLoansFillIcon {...svgFillIconProps} />,
    notesFill: <NotesFillIcon {...svgFillIconProps} />,
    paperclipFill: <PaperclipFillIcon {...svgFillIconProps} />,
    payslipFill: <PayslipFillIcon {...svgFillIconProps} />,
    penFill: <PenFillIcon {...svgFillIconProps} />,
    phoneFill: <PhoneFillIcon {...svgFillIconProps} />,
    pieChartFill: <PieChartFillIcon {...svgFillIconProps} />,
    qrCodeFill: <QrCodeFillIcon {...svgFillIconProps} />,
    questionFill: <QuestionFillIcon {...svgFillIconProps} />,
    refreshFill: <RefreshFillIcon {...svgFillIconProps} />,
    restartFill: <RestartFillIcon {...svgFillIconProps} />,
    scannerFill: <ScannerFillIcon {...svgFillIconProps} />,
    scheduleFill: <ScheduleFillIcon {...svgFillIconProps} />,
    settingsFill: <SettingsFillIcon {...svgFillIconProps} />,
    shieldCheckFill: <ShieldCheckFillIcon {...svgFillIconProps} />,
    shopFill: <ShopFillIcon {...svgFillIconProps} />,
    shoppingBasketFill: <ShoppingBasketFillIcon {...svgFillIconProps} />,
    shoppingCartFill: <ShoppingCartFillIcon {...svgFillIconProps} />,
    starFill: <StarFillIcon {...svgFillIconProps} />,
    suitcaseFill: <SuitcaseFillIcon {...svgFillIconProps} />,
    trashFill: <TrashFillIcon {...svgFillIconProps} />,
    tuningSquareFill: <TuningSquareFillIcon {...svgFillIconProps} />,
    unlinkFill: <UnlinkFillIcon {...svgFillIconProps} />,
    uploadFill: <UploadFillIcon {...svgFillIconProps} />,
    userFill: <UserFillIcon {...svgFillIconProps} />,
    walletFill: <WalletFillIcon {...svgFillIconProps} />,
    widgetFill: <WidgetFillIcon {...svgFillIconProps} />,
    addOutline: <AddOutlineIcon {...svgFillIconProps} />,
    arrowDownOutline: <ArrowDownOutlineIcon {...svgFillIconProps} />,
    arrowLeftOutline: <ArrowLeftOutlineIcon {...svgFillIconProps} />,
    arrowRightOutline: <ArrowRightOutlineIcon {...svgFillIconProps} />,
    arrowUpOutline: <ArrowUpOutlineIcon {...svgFillIconProps} />,
    attendanceOutline: <AttendanceOutlineIcon {...svgFillIconProps} />,
    bellOutline: <BellOutlineIcon {...svgFillIconProps} />,
    boxOutline: <BoxOutlineIcon {...svgFillIconProps} />,
    buildingsOutline: <BuildingsOutlineIcon {...svgFillIconProps} />,
    calendarArrowOutline: <CalendarArrowOutlineIcon {...svgFillIconProps} />,
    calendarCheckOutline: <CalendarCheckOutlineIcon {...svgFillIconProps} />,
    calendarCloseOutline: <CalendarCloseOutlineIcon {...svgFillIconProps} />,
    calendarOutline: <CalendarOutlineIcon {...svgFillIconProps} />,
    calendarMinimalisticOutline: (
      <CalendarMinimalisticOutlineIcon {...svgFillIconProps} />
    ),
    calendarPlusOutline: <CalendarPlusOutlineIcon {...svgFillIconProps} />,
    cameraOutline: <CameraOutlineIcon {...svgFillIconProps} />,
    cameraRotateOutline: <CameraRotateOutlineIcon {...svgFillIconProps} />,
    cardOutline: <CardOutlineIcon {...svgFillIconProps} />,
    caretDownOutline: <CaretDownOutlineIcon {...svgFillIconProps} />,
    caretLeftOutline: <CaretLeftOutlineIcon {...svgFillIconProps} />,
    caretRightOutline: <CaretRightOutlineIcon {...svgFillIconProps} />,
    caretUpOutline: <CaretUpOutlineIcon {...svgFillIconProps} />,
    chatOutline: <ChatOutlineIcon {...svgFillIconProps} />,
    checkOutline: <CheckOutlineIcon {...svgFillIconProps} />,
    clipboardAddOutline: <ClipboardAddOutlineIcon {...svgFillIconProps} />,
    clipboardCheckOutline: <ClipboardCheckOutlineIcon {...svgFillIconProps} />,
    clipboardEditOutline: <ClipboardEditOutlineIcon {...svgFillIconProps} />,
    clipboardListOutline: <ClipboardListOutlineIcon {...svgFillIconProps} />,
    clipboardOkayOutline: <ClipboardOkayOutlineIcon {...svgFillIconProps} />,
    clipboardSearchOutline: (
      <ClipboardSearchOutlineIcon {...svgFillIconProps} />
    ),
    clipboardTextOutline: <ClipboardTextOutlineIcon {...svgFillIconProps} />,
    clipboardTimeOutline: <ClipboardTimeOutlineIcon {...svgFillIconProps} />,
    clipboardWarningOutline: (
      <ClipboardWarningOutlineIcon {...svgFillIconProps} />
    ),
    clockCircleOutline: <ClockCircleOutlineIcon {...svgFillIconProps} />,
    closeOutline: <CloseOutlineIcon {...svgFillIconProps} />,
    copyOutline: <CopyOutlineIcon {...svgFillIconProps} />,
    dangerOutline: <DangerOutlineIcon {...svgFillIconProps} />,
    diagramUpOutline: <DiagramUpOutlineIcon {...svgFillIconProps} />,
    dialogOutline: <DialogOutlineIcon {...svgFillIconProps} />,
    disketteOutline: <DisketteOutlineIcon {...svgFillIconProps} />,
    documentAddOutline: <DocumentAddOutlineIcon {...svgFillIconProps} />,
    documentOutline: <DocumentOutlineIcon {...svgFillIconProps} />,
    doubleCaretDownOutline: (
      <DoubleCaretDownOutlineIcon {...svgFillIconProps} />
    ),
    doubleCaretLeftOutline: (
      <DoubleCaretLeftOutlineIcon {...svgFillIconProps} />
    ),
    doubleCaretRightOutline: (
      <DoubleCaretRightOutlineIcon {...svgFillIconProps} />
    ),
    doubleCaretUpOutline: <DoubleCaretUpOutlineIcon {...svgFillIconProps} />,
    downloadOutline: <DownloadOutlineIcon {...svgFillIconProps} />,
    emailOutline: <EmailOutlineIcon {...svgFillIconProps} />,
    eyeClosedOutline: <EyeClosedOutlineIcon {...svgFillIconProps} />,
    eyeOutline: <EyeOutlineIcon {...svgFillIconProps} />,
    fileOutline: <FileOutlineIcon {...svgFillIconProps} />,
    filterOutline: <FilterOutlineIcon {...svgFillIconProps} />,
    folderOutline: <FolderOutlineIcon {...svgFillIconProps} />,
    galleryAddOutline: <GalleryAddOutlineIcon {...svgFillIconProps} />,
    galleryOutline: <GalleryOutlineIcon {...svgFillIconProps} />,
    globalOutline: <GlobalOutlineIcon {...svgFillIconProps} />,
    gpsOutline: <GpsOutlineIcon {...svgFillIconProps} />,
    groupOutline: <GroupOutlineIcon {...svgFillIconProps} />,
    hamburgerMenuOutline: <HamburgerMenuOutlineIcon {...svgFillIconProps} />,
    hashtagOutline: <HashtagOutlineIcon {...svgFillIconProps} />,
    heartOutline: <HeartOutlineIcon {...svgFillIconProps} />,
    historyOutline: <HistoryOutlineIcon {...svgFillIconProps} />,
    homeOutline: <HomeOutlineIcon {...svgFillIconProps} />,
    infoOutline: <InfoOutlineIcon {...svgFillIconProps} />,
    keyOutline: <KeyOutlineIcon {...svgFillIconProps} />,
    linkOutline: <LinkOutlineIcon {...svgFillIconProps} />,
    loanSaleOutline: <LoanSaleOutlineIcon {...svgFillIconProps} />,
    lockKeyholeOutline: <LockKeyholeOutlineIcon {...svgFillIconProps} />,
    lockKeyholeUnlockedOutline: (
      <LockKeyholeUnlockedOutlineIcon {...svgFillIconProps} />
    ),
    loginOutline: <LoginOutlineIcon {...svgFillIconProps} />,
    logoutOutline: <LogoutOutlineIcon {...svgFillIconProps} />,
    magniferOutline: <MagniferOutlineIcon {...svgFillIconProps} />,
    mapPointOutline: <MapPointOutlineIcon {...svgFillIconProps} />,
    menuDotOutline: <MenuDotOutlineIcon {...svgFillIconProps} />,
    minusOutline: <MinusOutlineIcon {...svgFillIconProps} />,
    myLoansOutline: <MyLoansOutlineIcon {...svgFillIconProps} />,
    notesOutline: <NotesOutlineIcon {...svgFillIconProps} />,
    paperclipOutline: <PaperclipOutlineIcon {...svgFillIconProps} />,
    payslipOutline: <PayslipOutlineIcon {...svgFillIconProps} />,
    penOutline: <PenOutlineIcon {...svgFillIconProps} />,
    phoneOutline: <PhoneOutlineIcon {...svgFillIconProps} />,
    pieChartOutline: <PieChartOutlineIcon {...svgFillIconProps} />,
    qrCodeOutline: <QrCodeOutlineIcon {...svgFillIconProps} />,
    questionOutline: <QuestionOutlineIcon {...svgFillIconProps} />,
    refreshOutline: <RefreshOutlineIcon {...svgFillIconProps} />,
    restartOutline: <RestartOutlineIcon {...svgFillIconProps} />,
    scannerOutline: <ScannerOutlineIcon {...svgFillIconProps} />,
    scheduleOutline: <ScheduleOutlineIcon {...svgFillIconProps} />,
    settingsOutline: <SettingsOutlineIcon {...svgFillIconProps} />,
    shieldCheckOutline: <ShieldCheckOutlineIcon {...svgFillIconProps} />,
    shopOutline: <ShopOutlineIcon {...svgFillIconProps} />,
    shoppingBasketOutline: <ShoppingBasketOutlineIcon {...svgFillIconProps} />,
    shoppingCartOutline: <ShoppingCartOutlineIcon {...svgFillIconProps} />,
    starOutline: <StarOutlineIcon {...svgFillIconProps} />,
    suitcaseOutline: <SuitcaseOutlineIcon {...svgFillIconProps} />,
    trashOutline: <TrashOutlineIcon {...svgFillIconProps} />,
    tuningSquareOutline: <TuningSquareOutlineIcon {...svgFillIconProps} />,
    unlinkOutline: <UnlinkOutlineIcon {...svgFillIconProps} />,
    uploadOutline: <UploadOutlineIcon {...svgFillIconProps} />,
    userOutline: <UserOutlineIcon {...svgFillIconProps} />,
    walletOutline: <WalletOutlineIcon {...svgFillIconProps} />,
    widgetOutline: <WidgetOutlineIcon {...svgFillIconProps} />,
  };

  return iconName[name];
};
